language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    # This is broken at this time due to a phpspec issue.
    # @see https://github.com/jhedstrom/DrupalDriver/issues/172
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then composer remove "henrikbjorn/phpspec-code-coverage" --dev --no-update; fi
  - travis_retry composer require --prefer-source --no-interaction php-http/mock-client

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/phpspec run -c phpspec.yml.ci; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then vendor/bin/phpspec run; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
